import { IconType } from 'react-icons'

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
} from 'react-icons/hi2'

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from 'react-icons/pi'

import { FaDiscord, FaGithub, FaInstagram, FaLinkedin, FaXTwitter } from 'react-icons/fa6'

export const iconLibrary: Record<string, IconType> = {
  arrowRight: HiArrowRight,
  arrowUpRight: HiArrowUpRight,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  book: PiBookBookmarkDuotone,
  calendar: HiCalendarDays,
  check: HiCheck,
  checkCircle: HiCheckCircle,
  chevronDown: HiChevronDown,
  chevronLeft: HiChevronLeft,
  chevronRight: HiChevronRight,
  chevronUp: HiChevronUp,
  clipboard: HiClipboard,
  close: HiMiniXMark,
  discord: FaDiscord,
  email: HiEnvelope,
  errorCircle: HiExclamationCircle,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  gallery: PiImageDuotone,
  github: FaGithub,
  globe: HiMiniGlobeAsiaAustralia,
  grid: PiGridFourDuotone,
  helpCircle: HiMiniQuestionMarkCircle,
  home: PiHouseDuotone,
  instagram: FaInstagram,
  infoCircle: HiInformationCircle,
  linkedin: FaLinkedin,
  openLink: HiOutlineLink,
  person: PiUserCircleDuotone,
  refresh: HiOutlineArrowPath,
  warningTriangle: HiExclamationTriangle,
  x: FaXTwitter,
}
